export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
  { title: "2024", value: "2024" },
];

export const manufacturerModels: Record<string, string[]> = {
  Acura: ["MDX", "RDX", "TLX", "ILX"],
  "Alfa Romeo": ["Giulia", "Stelvio", "4C", "Spider"],
  "Aston Martin": ["DB11", "Vantage", "DBS", "Rapide"],
  Audi: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "Q8"],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga"],
  BMW: ["X1", "X3", "X5", "3 Series", "5 Series", "7 Series"],
  Buick: ["Enclave", "Encore", "Envision", "Regal"],
  Cadillac: ["Escalade", "XT5", "CT5", "CT6"],
  Chevrolet: ["Camaro", "Equinox", "Malibu", "Silverado"],
  Chrysler: ["300", "Pacifica", "Voyager"],
  Citroen: ["C3", "C4", "C5", "Berlingo"],
  Dodge: ["Challenger", "Charger", "Durango", "Journey"],
  Ferrari: ["488 GTB", "Portofino", "F8 Tributo", "Roma"],
  Fiat: ["500", "Panda", "500X", "Tipo"],
  Ford: ["F-150", "Mustang", "Explorer", "Escape"],
  GMC: ["Sierra", "Yukon", "Acadia", "Canyon"],
  Honda: ["Accord", "Civic", "CR-V", "Pilot"],
  Hyundai: ["Elantra", "Sonata", "Tucson", "Santa Fe"],
  Infiniti: ["Q50", "Q60", "QX50", "QX80"],
  Jaguar: ["F-Pace", "XE", "XF", "I-PACE"],
  Jeep: ["Cherokee", "Grand Cherokee", "Wrangler", "Compass"],
  Kia: ["Sorento", "Sportage", "K5", "Seltos"],
  Lamborghini: ["Huracan", "Aventador", "Urus"],
  "Land Rover": ["Range Rover", "Discovery", "Defender"],
  Lexus: ["RX", "ES", "NX", "LS"],
  Lincoln: ["Navigator", "Aviator", "Corsair", "Continental"],
  Maserati: ["Ghibli", "Levante", "Quattroporte"],
  Mazda: ["CX-5", "Mazda3", "Mazda6", "MX-5 Miata"],
  McLaren: ["720S", "570S", "Artura"],
  "Mercedes-Benz": ["C-Class", "E-Class", "S-Class", "GLE"],
  MINI: ["Cooper", "Countryman", "Clubman"],
  Mitsubishi: ["Outlander", "Eclipse Cross", "Mirage"],
  Nissan: ["Altima", "Rogue", "Sentra", "370Z"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera"],
  Ram: ["1500", "2500", "3500", "ProMaster"],
  "Rolls-Royce": ["Phantom", "Cullinan", "Ghost"],
  Subaru: ["Outback", "Forester", "Impreza", "Ascent"],
  Tesla: ["Model S", "Model 3", "Model X", "Model Y"],
  Toyota: ["Camry", "Corolla", "RAV4", "Highlander"],
  Volkswagen: ["Golf", "Passat", "Tiguan", "Jetta"],
  Volvo: ["XC90", "XC60", "S60", "V60"],
};

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electric",
    value: "Electric",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Insurance Information", url: "/" },
      { title: "Bussiness Relation", url: "/" },
      { title: "Cancellation Policy", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "About us", url: "/" },
      { title: "Contact us", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Press", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "TikTok", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
